
module InchCI
  module Config
    LANGUAGES_BUILD_LOCALLY = %w(Ruby JavaScript)
    LANGUAGES_BUILD_EXTERNALLY = %w(Elixir)
    LANGUAGES = LANGUAGES_BUILD_LOCALLY + LANGUAGES_BUILD_EXTERNALLY

    MIN_RELEVANT_PRIORITY = 0
  end
end
